DATA:
  TRAIN_DATASET:
    NAME: "flyingchairs"
    ROOT_DIR: "../../../Datasets/FlyingChairs_release/data"
  VAL_DATASET:
    NAME: "flyingchairs"
    ROOT_DIR: "../../../Datasets/FlyingChairs_release/data" 
  BATCH_SIZE: 8
  NUM_WORKERS: 1
  PIN_MEMORY: True
  APPEND_VALID_MASK: False
  TRAIN_CROP_SIZE: [384, 448]
  VAL_CROP_SIZE: [384, 448]
  AUGMENTATION:
    USE: True
    PARAMS:
      TRAINING:
        SPATIAL_AUG_PARAMS: {"aug_prob": 0.5, "stretch_prob": 0.5, "min_scale": -0.1, "max_scale": 1.0, "flip": True, "h_flip_prob": 0.5, "v_flip_prob": 0.5}
        COLOR_AUG_PARAMS: {"aug_prob": 0.5, "brightness": 0.5, "contrast": 0.5, "saturation": 0.5, "hue": 0.5}
        ERASER_AUG_PARAMS: {"aug_prob": 0.0}
      VALIDATION:
        SPATIAL_AUG_PARAMS: {"aug_prob": 0.0}
        COLOR_AUG_PARAMS: {"aug_prob": 0.0}
        ERASER_AUG_PARAMS: {"aug_prob": 0.0}
OPTIMIZER:
  NAME: Adam
  LR: 0.0001
  PARAMS:
    weight_decay: 0.0004
    betas: [0.9, 0.999]
SCHEDULER:
  USE: True
  NAME: MultiStepLR
  PARAMS:
    milestones: [144, 216, 288, 360]
    gamma: 0.5
CRITERION:
  CUSTOM: True
  NAME: MultiScaleLossV2
  PARAMS:
    norm: "l2" 
    weights: [0.32, 0.08, 0.02, 0.01, 0.005] 
GRAD_CLIP: 
  USE: False
  VALUE: 1.0
TARGET_SCALE_FACTOR: 20.0
MIXED_PRECISION: False
DEVICE: "0"
DISTRIBUTED:
  USE: False
  WORLD_SIZE: 2
  BACKEND: nccl
  MASTER_ADDR: localhost
  MASTER_PORT: "12355"
LOG_DIR: "./logs"
LOG_ITERATIONS_INTERVAL: 100
CKPT_DIR: "./ckpts"
CKPT_INTERVAL: 1
VALIDATE_INTERVAL: 1
VALIDATE_ON: metric
EPOCHS: 432
NUM_STEPS: null
RESUME_TRAINING:
  CONSOLIDATED_CKPT: null
  EPOCHS: 100
  START_EPOCH: null