NAME: GMFlowV2
ENCODER:
  NAME: NAT
  IN_CHANNELS: 3
  DEPTHS: [8, 12]
  NUM_HEADS: [2, 4]
  EMBED_DIMS: 64
  MLP_RATIO: 3
  DROP_PATH_RATE: 0.2
  KERNEL_SIZE: 7
  DILATIONS: None
  USE_SINE_POS_EMBED: True
  SELF_NO_FFN: True
  CROSS_NO_FFN: False
MODEL:
  FEATURE_CHANNELS: 128
  NUM_SCALES: 1
  UPSAMPLE_FACTOR: 8
  NUM_HEADS: 1
  ATTENTION_TYPE: "swin"
  FFN_DIM_EXPANSION: 4
  NUM_TRANSFORMER_LAYERS: 6
  ATTN_SPLITS_LIST: [2]
  CORR_RADIUS_LIST: [-1]
  PROP_RADIUS_LIST: [-1]
  PRED_BIDIR_FLOW: False
