NAME: GMFlow
ENCODER:
  NAME: DinoVITS8
  FREEZE: False
  PRETRAINED_CKPT_PATH: "../dino_vit_pretrained/dino_deitsmall8_pretrain.pth"
MODEL:
  FEATURE_CHANNELS: 384
  NUM_SCALES: 1
  UPSAMPLE_FACTOR: 8
  NUM_HEADS: 1
  ATTENTION_TYPE: "swin"
  FFN_DIM_EXPANSION: 4
  NUM_TRANSFORMER_LAYERS: 6
  ATTN_SPLITS_LIST: [2]
  CORR_RADIUS_LIST: [-1]
  PROP_RADIUS_LIST: [-1]
  PRED_BIDIR_FLOW: False
  USE_SINE_POS_EMBED: True
