NAME: GMFlow
ENCODER:
  NAME: SwinEncoderV2
  IN_CHANNELS: 3
  EMBEDDING_CHANNELS: 64
  DEPTHS: [4, 6]
  INPUT_RESOLUTION: [384, 512]
  NUMBER_OF_HEADS: [8, 16]
  WINDOW_SIZE: 8
  PATCH_SIZE: 4
  FF_FEATURE_RATIO: 4
  DROPOUT_PATH: 0.1
  DROPOUT: 0.0
  DROPOUT_ATTENTION: 0.0
  USE_CHECKPOINT: False
  SEQUENTIAL_SELF_ATTENTION: False
MODEL:
  FEATURE_CHANNELS: 128
  NUM_SCALES: 1
  UPSAMPLE_FACTOR: 8
  NUM_HEADS: 1
  ATTENTION_TYPE: "swin"
  FFN_DIM_EXPANSION: 4
  NUM_TRANSFORMER_LAYERS: 6
  ATTN_SPLITS_LIST: [2]
  CORR_RADIUS_LIST: [-1]
  PROP_RADIUS_LIST: [-1]
  PRED_BIDIR_FLOW: False
  USE_SINE_POS_EMBED: True
