NAME: GMFlowV2
ENCODER:
  NAME: BasicEncoder
  IN_CHANNELS: 3
  OUT_CHANNELS: 128
  NORM: instance
  P_DROPOUT: 0.0
  LAYER_CONFIG: [64, 96, 128]
  INTERMEDIATE_FEATURES: False
MODEL:
  FEATURE_CHANNELS: 128
  NUM_SCALES: 1
  UPSAMPLE_FACTOR: 8
  NUM_HEADS: 1
  ATTENTION_TYPE: "swin"
  FFN_DIM_EXPANSION: 4
  NUM_TRANSFORMER_LAYERS: 6
  ATTN_SPLITS_LIST: [2]
  CORR_RADIUS_LIST: [-1]
  PROP_RADIUS_LIST: [-1]
  PRED_BIDIR_FLOW: False
  USE_SINE_POS_EMBED: True
