NAME: FlowNetC_V2
ENCODER:
  NAME: BasicEncoderV2
  IN_CHANNELS: 3
  OUT_CHANNELS: 256
  NORM: none
  P_DROPOUT: 0.0
  LAYER_CONFIG: [64, 128, 256]
  CORR_CONFIG: [512, 512, 1024]
  CONFIG: [64, 128, 256, 256, 512, 512, 512, 512, 1024, 1024]
  INTERMEDIATE_FEATURES: True
SIMILARITY:
  NAME: IterSpatialCorrelationSampler
  PAD_SIZE: 0
  MAX_DISPLACEMENT: 10
DECODER:
  NAME: FlowNetConvDecoder
  IN_CHANNELS: 1024
  CONFIG: [512, 256, 128, 64]