DATA:
  TRAIN_DATASET:
    NAME: "flyingthings3d"
    ROOT_DIR: "../../../Datasets/SceneFlow/FlyingThings3D"
  VAL_DATASET:
    NAME: "flyingthings3d"
    ROOT_DIR: "../../../Datasets/SceneFlow/FlyingThings3D" 
  BATCH_SIZE: 6
  NUM_WORKERS: 1
  PIN_MEMORY: True
  APPEND_VALID_MASK: True
  SHUFFLE: True
  TRAIN_CROP_SIZE: [384, 768]
  VAL_CROP_SIZE: [384, 768]
  AUGMENTATION:
    USE: True
    PARAMS:
      TRAINING:
        SPATIAL_AUG_PARAMS: {"enabled": True, "aug_prob": 0.5, "stretch_prob": 0.5, "min_scale": -0.1, "max_scale": 1.0, "flip": True, "h_flip_prob": 0.5, "v_flip_prob": 0.5}
        COLOR_AUG_PARAMS: {"enabled": True, "aug_prob": 0.5, "brightness": 0.5, "contrast": 0.5, "saturation": 0.5, "hue": 0.5}
        ERASER_AUG_PARAMS: {"enabled": True, "aug_prob": 0.5, "bounds": [50,100]}
      VALIDATION:
        SPATIAL_AUG_PARAMS: {"enabled": False, "aug_prob": 0.0}
        COLOR_AUG_PARAMS: {"enabled": False, "aug_prob": 0.0}
        ERASER_AUG_PARAMS: {"enabled": False, "aug_prob": 0.0}
OPTIMIZER:
  NAME: AdamW
  LR: 0.000125
  PARAMS:
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-08
    amsgrad: False
SCHEDULER:
  USE: True
  NAME: OneCycleLR
  PARAMS:
    max_lr: 0.000125
    total_steps: 100100
    pct_start: 0.05
    cycle_momentum: False
    anneal_strategy: linear
CRITERION:
  CUSTOM: True
  NAME: SequenceLoss
  PARAMS: 
    gamma: 0.8
    max_flow: 400.0
GRAD_CLIP: 
  USE: True
  VALUE: 1.0
TARGET_SCALE_FACTOR: 1.0
MIXED_PRECISION: False
DEVICE: "0"
DISTRIBUTED:
  USE: False
  WORLD_SIZE: 2
  BACKEND: nccl
  MASTER_ADDR: localhost
  MASTER_PORT: "12355"
LOG_DIR: "./logs"
LOG_ITERATIONS_INTERVAL: 100
CKPT_DIR: "./ckpts"
CKPT_INTERVAL: 20000
VALIDATE_INTERVAL: 1000
VALIDATE_ON: metric
EPOCHS: null
NUM_STEPS: 100100
RESUME_TRAINING:
  CONSOLIDATED_CKPT: null
  EPOCHS: 100
  START_EPOCH: null