NAME: PWCNet
ENCODER:
  NAME: BasicEncoderV2
  IN_CHANNELS: 3
  OUT_CHANNELS: 196
  NORM: none
  P_DROPOUT: 0.0
  LAYER_CONFIG: [16, 32, 64, 96, 128, 196]
  INTERMEDIATE_FEATURES: True
DECODER:
  NAME: PyramidDecoder
  CONFIG: [128, 128, 96, 64, 32]
  TO_FLOW: True
  SIMILARITY:
    PAD_SIZE: 0
    MAX_DISPLACEMENT: 4
  FLOW_SCALE_FACTOR: 20.0