_BASE_: "./kubric_improved_aug.yaml"
TARGET_SCALE_FACTOR: 20.0
DATA:
  AUGMENTATION:
    PARAMS:
      TRAINING:
        NOISE_AUG_PARAMS: {
          "enabled": True,
          "aug_prob": 1.0,
          "noise_std_range": 0.06 
        }